"""Added img_file and user_id to Posts table

Revision ID: a3f5e5e8782f
Revises: 
Create Date: 2025-03-05 10:50:54.495016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3f5e5e8782f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('ph_no',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=12),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('img_file',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('img_file',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('ph_no',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
